# Generated by Django 3.2.9 on 2021-11-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.CharField(blank=True, choices=[('Sci-Fi', 'Sci-Fi'), ('Fantasy', 'Fantasy'), ('History', 'History'), ('Comics', 'Comics'), ('Poetry', 'Poetry')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(blank=True, default='1', null=True),
        ),
    ]
